# The user that you will use to serve as the bot connection to Codecov
# This bot user must have permissions on the repo and Codecov (by logging in)

codecov:
  bot: <bot-username> #this is a username for Github/Gitlab/Bitbucket
